package Presentation;

import Business.Customer;
import Business.DataIO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Payden Boughton
 */
    public class FloorGUI extends javax.swing.JFrame {

    public FloorGUI() {
        initComponents();
        //centers the GUI
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFloor = new javax.swing.ButtonGroup();
        tPCustomer = new javax.swing.JTabbedPane();
        jpCustomerInfo = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblAddr = new javax.swing.JLabel();
        addrTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        jpFloorSelector = new javax.swing.JPanel();
        lblFloorType = new javax.swing.JLabel();
        woodRadBtn = new javax.swing.JRadioButton();
        carpetRadBtn = new javax.swing.JRadioButton();
        btnCalc = new javax.swing.JButton();
        widTextField = new javax.swing.JTextField();
        lenTextField = new javax.swing.JTextField();
        lblLength = new javax.swing.JLabel();
        lblWidth = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jpOrder = new javax.swing.JPanel();
        costTextField = new javax.swing.JTextField();
        btnOrder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaOrderSummary = new javax.swing.JTextArea();
        lblSummary = new javax.swing.JLabel();
        areaTextField = new javax.swing.JTextField();
        lblFloorArea = new javax.swing.JLabel();
        lblFloorCost = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        lblFloorEstimatorLogo = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        btnGit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setText("Please Enter Your Name");

        lblAddr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddr.setText("Please Enter Your Address");

        javax.swing.GroupLayout jpCustomerInfoLayout = new javax.swing.GroupLayout(jpCustomerInfo);
        jpCustomerInfo.setLayout(jpCustomerInfoLayout);
        jpCustomerInfoLayout.setHorizontalGroup(
            jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCustomerInfoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAddr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addrTextField))
                .addGap(44, 44, 44))
        );
        jpCustomerInfoLayout.setVerticalGroup(
            jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCustomerInfoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddr)
                    .addComponent(lblName))
                .addGap(29, 29, 29)
                .addGroup(jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        tPCustomer.addTab("Customer Information", jpCustomerInfo);

        lblFloorType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFloorType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFloorType.setText("Please Select Floor Type");

        btnGroupFloor.add(woodRadBtn);
        woodRadBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        woodRadBtn.setText("Wood $20 sq.ft");

        btnGroupFloor.add(carpetRadBtn);
        carpetRadBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        carpetRadBtn.setText("Carpet $10 sq.ft");

        btnCalc.setText("Calculate");
        btnCalc.setDoubleBuffered(true);
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        lblLength.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLength.setText("Enter Length");

        lblWidth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWidth.setText("Enter Width");

        javax.swing.GroupLayout jpFloorSelectorLayout = new javax.swing.GroupLayout(jpFloorSelector);
        jpFloorSelector.setLayout(jpFloorSelectorLayout);
        jpFloorSelectorLayout.setHorizontalGroup(
            jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                        .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLength)
                            .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                                .addComponent(lenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(carpetRadBtn)
                                            .addComponent(lblFloorType)
                                            .addComponent(woodRadBtn)))
                                    .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                                        .addGap(261, 261, 261)
                                        .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblWidth)
                                            .addComponent(widTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpFloorSelectorLayout.setVerticalGroup(
            jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFloorType)
                .addGap(18, 18, 18)
                .addComponent(woodRadBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carpetRadBtn)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLength)
                    .addComponent(lblWidth))
                .addGap(15, 15, 15)
                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(widTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tPCustomer.addTab("Floor Type Selector", jpFloorSelector);

        costTextField.setEditable(false);

        btnOrder.setText("Place Order");
        btnOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrder.setPreferredSize(new java.awt.Dimension(90, 25));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        txaOrderSummary.setEditable(false);
        txaOrderSummary.setColumns(20);
        txaOrderSummary.setRows(5);
        jScrollPane2.setViewportView(txaOrderSummary);

        lblSummary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSummary.setText("Order Summary");

        areaTextField.setEditable(false);

        lblFloorArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFloorArea.setText("Floor Area");

        lblFloorCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFloorCost.setText("Floor Cost");

        javax.swing.GroupLayout jpOrderLayout = new javax.swing.GroupLayout(jpOrder);
        jpOrder.setLayout(jpOrderLayout);
        jpOrderLayout.setHorizontalGroup(
            jpOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpOrderLayout.createSequentialGroup()
                        .addComponent(lblFloorArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFloorCost))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpOrderLayout.createSequentialGroup()
                        .addGroup(jpOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpOrderLayout.createSequentialGroup()
                                .addComponent(areaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpOrderLayout.createSequentialGroup()
                                .addGap(0, 168, Short.MAX_VALUE)
                                .addGroup(jpOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpOrderLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblSummary))
                                    .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)))
                        .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpOrderLayout.setVerticalGroup(
            jpOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFloorArea)
                    .addComponent(lblFloorCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSummary)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tPCustomer.addTab("Order", jpOrder);

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CustomerTable", "Customer Address", "Floor Type", "Floor Area", "Floor Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );

        tPCustomer.addTab("Order Table", jPanel1);

        lblFloorEstimatorLogo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFloorEstimatorLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/icon.png"))); // NOI18N
        lblFloorEstimatorLogo.setText("Flooring Estimator");

        btnLoad.setText("Load Order Table");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        jMenu.setText("Help");

        btnGit.setText("Git ReadMe");
        btnGit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGitActionPerformed(evt);
            }
        });
        jMenu.add(btnGit);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFloorEstimatorLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoad)
                .addContainerGap())
            .addComponent(tPCustomer)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFloorEstimatorLogo)
                    .addComponent(btnLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPCustomer))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // DONE add your handling code here:
           String floorType = "",cName = "",cAddr = "";
               double myLength, myWidth;
        myLength = Double.parseDouble(lenTextField.getText());
        myWidth = Double.parseDouble(widTextField.getText());
        cName = nameTextField.getText();
        cAddr = addrTextField.getText();
        if (carpetRadBtn.isSelected()){
            floorType = "Carpet";
        }
        if (woodRadBtn.isSelected()){
            floorType = "Wood"; 
        } 
        Customer cus = new Customer(cName,cAddr,floorType,myLength,myWidth);
        //calculating area
        double floorArea = cus.getFloorArea();
        
        //verifying area is calculated then moving on to check if all fields are entered
        if(floorArea == 0){
            JOptionPane.showMessageDialog(rootPane, "Please Calulate your Total");
        }
        else{
            if (nameTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Must Enter a Name","Name is Missing",JOptionPane.ERROR_MESSAGE);
                nameTextField.requestFocus();
                return;
            }
            if (addrTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Must Enter an Address","Address is Missing",JOptionPane.ERROR_MESSAGE);
                addrTextField.requestFocus();
                return;
            }

            //check if none are selected
            if(!carpetRadBtn.isSelected() && !woodRadBtn.isSelected()){
                JOptionPane.showMessageDialog(null, "Please select A floor type","No Floor Type Selected",JOptionPane.ERROR_MESSAGE);
                return;
            }
            
        DataIO data = new DataIO();
        //save the data
        try{
        data.saveData(cus);
        }   catch (SQLException ex) { 
                Logger.getLogger(FloorGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }   
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnGitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGitActionPerformed
        //links to github
        try { 
         String url = "https://github.com/Distantone/FlooringEstimator/tree/master/src";
         java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
       }
       catch (java.io.IOException e) {
           System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_btnGitActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // DONE add your handling code here:
           String floorType;
        
        //check for empty fields
        if(!carpetRadBtn.isSelected() && !woodRadBtn.isSelected()){
            JOptionPane.showMessageDialog(null, "Please select A floor type","No Floor Type Selected",JOptionPane.ERROR_MESSAGE);
        }
        if (lenTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter a Length","No Length Entered",JOptionPane.ERROR_MESSAGE);
            lenTextField.requestFocus();
            return;
        }
        if (widTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter a Length","No Length Entered",JOptionPane.ERROR_MESSAGE);
            widTextField.requestFocus();
            return;
        }
        Customer cus = new Customer();
        double myLength, myWidth;

        //grab myLength and myWidth from the textfields then convert string to double on mylength and myWidth
        myLength = Double.parseDouble(lenTextField.getText());
        myWidth = Double.parseDouble(widTextField.getText());
        //set everything up to be calculated
        cus.setLength(myLength);
        cus.setWidth(myWidth);
        if (carpetRadBtn.isSelected()){
            floorType = "Carpet";
            cus.setFloorType(floorType);
        }
        if (woodRadBtn.isSelected()){
            floorType = "Wood";
            cus.setFloorType(floorType);
        }
        areaTextField.setText("" + cus.getFloorArea());
        String TotalAsString = String.format("%.2f", cus.getFloorCost());
        //set the total
        costTextField.setText("$" + TotalAsString);

        JOptionPane.showMessageDialog(rootPane, "Total Has been Calculated on Order Tab");
    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod = new DefaultTableModel(new String[]{"CustomerName", "CustomerAddress", "FloorType", "FloorArea", "FloorCost"}, 0);
        DataIO data = new DataIO();

        try {
            mod =  data.loadData();
        } catch (SQLException ex) {
            Logger.getLogger(FloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        customerTable.setModel(mod);
    }//GEN-LAST:event_btnLoadActionPerformed

    public void orderSum(String name,String addr,String fType, double fArea, double totalCost){
        //displays customer data in order summary
        txaOrderSummary.setText(
        "Customer: " + name + "\n"
        + "Customer Address: " + addr + "\n"       
        + "Floor Type: " + fType +"\n"
        + "Floor Area: " + fArea + "\n"
        + "Floor Cost: " + totalCost + "\n"       
        );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FloorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FloorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FloorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FloorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FloorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrTextField;
    private javax.swing.JTextField areaTextField;
    private javax.swing.JButton btnCalc;
    private javax.swing.JMenuItem btnGit;
    private javax.swing.ButtonGroup btnGroupFloor;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnOrder;
    private javax.swing.JRadioButton carpetRadBtn;
    private javax.swing.JTextField costTextField;
    private javax.swing.JTable customerTable;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpCustomerInfo;
    private javax.swing.JPanel jpFloorSelector;
    private javax.swing.JPanel jpOrder;
    private javax.swing.JLabel lblAddr;
    private javax.swing.JLabel lblFloorArea;
    private javax.swing.JLabel lblFloorCost;
    private javax.swing.JLabel lblFloorEstimatorLogo;
    private javax.swing.JLabel lblFloorType;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSummary;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JTextField lenTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTabbedPane tPCustomer;
    private javax.swing.JTextArea txaOrderSummary;
    private javax.swing.JTextField widTextField;
    private javax.swing.JRadioButton woodRadBtn;
    // End of variables declaration//GEN-END:variables
}
