package Presentation;

import Business.Customer;
import Business.DataIO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Payden Boughton
 */
public class FloorGUI extends javax.swing.JFrame {

    public FloorGUI() {
        initComponents();
        //centers the GUI
        this.setLocationRelativeTo(null);
        //load initial table data
        Ldata();
        secur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFloor = new javax.swing.ButtonGroup();
        tPCustomer = new javax.swing.JTabbedPane();
        jpCustomerInfo = new javax.swing.JPanel();
        lblFName = new javax.swing.JLabel();
        lblAddr = new javax.swing.JLabel();
        txfCity = new javax.swing.JTextField();
        txfFName = new javax.swing.JTextField();
        btnCusContinue = new javax.swing.JButton();
        lblLName = new javax.swing.JLabel();
        txfLName = new javax.swing.JTextField();
        txfAddr = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        cbState = new javax.swing.JComboBox<>();
        lblState = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpFloorSelector = new javax.swing.JPanel();
        lblFloorType = new javax.swing.JLabel();
        woodRadBtn = new javax.swing.JRadioButton();
        carpetRadBtn = new javax.swing.JRadioButton();
        btnCalc = new javax.swing.JButton();
        widTextField = new javax.swing.JTextField();
        lenTextField = new javax.swing.JTextField();
        lblLength = new javax.swing.JLabel();
        lblWidth = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        areaTextField = new javax.swing.JTextField();
        lblFloorArea1 = new javax.swing.JLabel();
        lblFloorCost1 = new javax.swing.JLabel();
        costTextField = new javax.swing.JTextField();
        btnTypeBack = new javax.swing.JButton();
        btnTypeContinue = new javax.swing.JButton();
        lblFloorSelector = new javax.swing.JLabel();
        jpOrder = new javax.swing.JPanel();
        btnOrder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaOrderSummary = new javax.swing.JTextArea();
        lblSummary = new javax.swing.JLabel();
        lblOrder = new javax.swing.JLabel();
        btnADMIN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        lblFloorEstimatorLogo = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        btnGit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Floor Estimator");

        tPCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPCustomerMouseClicked(evt);
            }
        });

        lblFName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFName.setText("First Name");

        lblAddr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddr.setText("Address");

        btnCusContinue.setText("Continue");
        btnCusContinue.setDoubleBuffered(true);
        btnCusContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCusContinueActionPerformed(evt);
            }
        });

        lblLName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLName.setText("Last Name");

        lblCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCity.setText("City");

        cbState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AK", "AL", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY" }));

        lblState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblState.setText("State");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Customer Information");

        javax.swing.GroupLayout jpCustomerInfoLayout = new javax.swing.GroupLayout(jpCustomerInfo);
        jpCustomerInfo.setLayout(jpCustomerInfoLayout);
        jpCustomerInfoLayout.setHorizontalGroup(
            jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCustomerInfoLayout.createSequentialGroup()
                .addGroup(jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCustomerInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCustomerInfoLayout.createSequentialGroup()
                                .addGroup(jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFName)
                                    .addComponent(txfFName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblState)
                                    .addComponent(txfAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbState, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAddr)))
                            .addGroup(jpCustomerInfoLayout.createSequentialGroup()
                                .addComponent(txfLName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txfCity, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCustomerInfoLayout.createSequentialGroup()
                                .addComponent(lblLName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCity)
                                .addGap(135, 135, 135))))
                    .addGroup(jpCustomerInfoLayout.createSequentialGroup()
                        .addGroup(jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCustomerInfoLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel1))
                            .addGroup(jpCustomerInfoLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(btnCusContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 131, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpCustomerInfoLayout.setVerticalGroup(
            jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCustomerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddr)
                    .addComponent(lblFName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfFName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(lblLName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfCity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfLName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnCusContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tPCustomer.addTab("Customer Information", jpCustomerInfo);

        lblFloorType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFloorType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFloorType.setText("Please Select Floor Type");

        btnGroupFloor.add(woodRadBtn);
        woodRadBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        woodRadBtn.setText("Wood $20 sq.ft");

        btnGroupFloor.add(carpetRadBtn);
        carpetRadBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        carpetRadBtn.setText("Carpet $10 sq.ft");

        btnCalc.setText("Calculate");
        btnCalc.setDoubleBuffered(true);
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        lblLength.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLength.setText("Enter Length");

        lblWidth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWidth.setText("Enter Width");

        areaTextField.setEditable(false);

        lblFloorArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFloorArea1.setText("Floor Area");

        lblFloorCost1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFloorCost1.setText("Floor Cost");

        costTextField.setEditable(false);

        btnTypeBack.setText("Back");
        btnTypeBack.setDoubleBuffered(true);
        btnTypeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTypeBackActionPerformed(evt);
            }
        });

        btnTypeContinue.setText("Continue");
        btnTypeContinue.setDoubleBuffered(true);
        btnTypeContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTypeContinueActionPerformed(evt);
            }
        });

        lblFloorSelector.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFloorSelector.setText("Floor Selector");

        javax.swing.GroupLayout jpFloorSelectorLayout = new javax.swing.GroupLayout(jpFloorSelector);
        jpFloorSelector.setLayout(jpFloorSelectorLayout);
        jpFloorSelectorLayout.setHorizontalGroup(
            jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnTypeBack, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnTypeContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(woodRadBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(carpetRadBtn)
                .addGap(75, 75, 75))
            .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                        .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLength)
                            .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                                        .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(areaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(263, 263, 263))
                                    .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                                        .addComponent(lblFloorArea1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)))
                                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblWidth)
                                    .addComponent(widTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFloorCost1))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(lblFloorType))
                    .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblFloorSelector)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFloorSelectorLayout.setVerticalGroup(
            jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFloorSelectorLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblFloorSelector)
                .addGap(18, 18, 18)
                .addComponent(lblFloorType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carpetRadBtn)
                    .addComponent(woodRadBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLength)
                    .addComponent(lblWidth))
                .addGap(18, 18, 18)
                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(widTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFloorCost1)
                        .addComponent(lblFloorArea1))
                    .addComponent(btnCalc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpFloorSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTypeBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTypeContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tPCustomer.addTab("Floor Type Selector", jpFloorSelector);

        btnOrder.setText("Place Order");
        btnOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrder.setMaximumSize(new java.awt.Dimension(77, 23));
        btnOrder.setMinimumSize(new java.awt.Dimension(77, 23));
        btnOrder.setPreferredSize(new java.awt.Dimension(77, 23));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        txaOrderSummary.setEditable(false);
        txaOrderSummary.setColumns(20);
        txaOrderSummary.setRows(5);
        jScrollPane2.setViewportView(txaOrderSummary);

        lblSummary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSummary.setText("Order Summary");

        lblOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOrder.setText("Order");

        btnADMIN.setText("Admin Access");
        btnADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADMINActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpOrderLayout = new javax.swing.GroupLayout(jpOrder);
        jpOrder.setLayout(jpOrderLayout);
        jpOrderLayout.setHorizontalGroup(
            jpOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpOrderLayout.createSequentialGroup()
                        .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSummary)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpOrderLayout.createSequentialGroup()
                        .addComponent(btnADMIN)
                        .addGap(122, 122, 122)
                        .addGroup(jpOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpOrderLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(jpOrderLayout.createSequentialGroup()
                                .addComponent(lblOrder)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jpOrderLayout.setVerticalGroup(
            jpOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOrderLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblOrder)
                .addGap(18, 18, 18)
                .addGroup(jpOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSummary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jpOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpOrderLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpOrderLayout.createSequentialGroup()
                        .addComponent(btnADMIN)
                        .addGap(25, 25, 25))))
        );

        tPCustomer.addTab("Order Summary", jpOrder);

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CustomerTable", "Customer Address", "Floor Type", "Floor Area", "Floor Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        tPCustomer.addTab("Order Table", jPanel1);

        lblFloorEstimatorLogo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFloorEstimatorLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/icon.png"))); // NOI18N
        lblFloorEstimatorLogo.setText("Flooring Estimator");

        btnLoad.setText("Load Order Table");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        jMenu.setText("Help");

        btnGit.setText("Git ReadMe");
        btnGit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGitActionPerformed(evt);
            }
        });
        jMenu.add(btnGit);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFloorEstimatorLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoad)
                .addContainerGap())
            .addComponent(tPCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFloorEstimatorLogo)
                    .addComponent(btnLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPCustomer))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // DONE add your handling code here:
        String floorType = "", cName = "", cAddr = "";
        double myLength, myWidth;
        myLength = Double.parseDouble(lenTextField.getText());
        myWidth = Double.parseDouble(widTextField.getText());
        //start Customer name String
        
        StringBuilder customerStr = new StringBuilder();
        customerStr.append(txfFName.getText());
        customerStr.append(" " + txfLName.getText());
        
        
        //start address string
        StringBuilder addrStr = new StringBuilder();
       
        addrStr.append(txfAddr.getText());
        addrStr.append(" " + txfCity.getText());
        addrStr.append(" " + cbState.getSelectedItem());
         
        cName = customerStr.toString();
        cAddr = addrStr.toString();
        if (carpetRadBtn.isSelected()) {
            floorType = "Carpet";
        }
        if (woodRadBtn.isSelected()) {
            floorType = "Wood";
        }
        Customer cus = new Customer(cName, cAddr, floorType, myLength, myWidth);
        //calculating area
        double floorArea = cus.getFloorArea();

        //verifying area is calculated then moving on to check if all fields are entered
        if (floorArea == 0) {
            JOptionPane.showMessageDialog(rootPane, "Please Calulate your Total");
        } else {
            if (txfFName.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Must Enter a First Name", "First Name is Missing", JOptionPane.ERROR_MESSAGE);
                txfFName.requestFocus();
                return;
            }
            if (txfLName.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Must Enter a Last Name", "Last Name is Missing", JOptionPane.ERROR_MESSAGE);
                txfLName.requestFocus();
                return;
            }
            
            if (txfAddr.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Must Enter an Address", "Address is Missing", JOptionPane.ERROR_MESSAGE);
                txfAddr.requestFocus();
                return;
            }
            if (txfCity.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Must Enter an City", "Address is Missing", JOptionPane.ERROR_MESSAGE);
                txfCity.requestFocus();
                return;
            }

            //check if none are selected
            if (!carpetRadBtn.isSelected() && !woodRadBtn.isSelected()) {
                JOptionPane.showMessageDialog(null, "Please select A floor type", "No Floor Type Selected", JOptionPane.ERROR_MESSAGE);
                return;
            }

            DataIO data = new DataIO();
            //save the data
            try {
                data.saveData(cus);
            } catch (SQLException ex) {
                Logger.getLogger(FloorGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        txaOrderSummary.setText(cus.toString());
        //reload table data with new data
        Ldata();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnGitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGitActionPerformed
        //links to github
        try {
            String url = "https://github.com/Distantone/FlooringEstimator/tree/master/src";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnGitActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // DONE add your handling code here:
        String floorType;

        //check for empty fields
        if (!carpetRadBtn.isSelected() && !woodRadBtn.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please select A floor type", "No Floor Type Selected", JOptionPane.ERROR_MESSAGE);
        }
        if (lenTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a Length", "No Length Entered", JOptionPane.ERROR_MESSAGE);
            lenTextField.requestFocus();
            return;
        }
        if (widTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a Length", "No Length Entered", JOptionPane.ERROR_MESSAGE);
            widTextField.requestFocus();
            return;
        }
        Customer cus = new Customer();
        double myLength, myWidth;

        //grab myLength and myWidth from the textfields then convert string to double on mylength and myWidth
        myLength = Double.parseDouble(lenTextField.getText());
        myWidth = Double.parseDouble(widTextField.getText());
        //set everything up to be calculated
        cus.setLength(myLength);
        cus.setWidth(myWidth);
        if (carpetRadBtn.isSelected()) {
            floorType = "Carpet";
            cus.setFloorType(floorType);
        }
        if (woodRadBtn.isSelected()) {
            floorType = "Wood";
            cus.setFloorType(floorType);
        }
        areaTextField.setText("" + cus.getFloorArea());
        String TotalAsString = String.format("%.2f", cus.getFloorCost());
        //set the total
        costTextField.setText("$" + TotalAsString);

    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod = new DefaultTableModel(new String[]{"CustomerName", "CustomerAddress", "FloorType", "FloorArea", "FloorCost"}, 0);
        DataIO data = new DataIO();

        try {
            mod = data.loadData();
        } catch (SQLException ex) {
            Logger.getLogger(FloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        customerTable.setModel(mod);
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnCusContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCusContinueActionPerformed
        // Continue button on first page(tab)
        if(evt.getSource() == btnCusContinue) {
     // check if we are at zero //
     if(tPCustomer.getSelectedIndex() == 0)
       tPCustomer.setSelectedIndex( tPCustomer.getTabCount() - 3);
     else
       tPCustomer.setSelectedIndex(tPCustomer.getSelectedIndex() -1);

  }

    }//GEN-LAST:event_btnCusContinueActionPerformed

    private void btnTypeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTypeBackActionPerformed
        // back button on Floor type selector page
        if(evt.getSource() == btnTypeBack) {
     // check if we are at zero //
     if(tPCustomer.getSelectedIndex() == 0)
       tPCustomer.setSelectedIndex( tPCustomer.getTabCount() - 4);
     else
       tPCustomer.setSelectedIndex(tPCustomer.getSelectedIndex() -1);

  }
    }//GEN-LAST:event_btnTypeBackActionPerformed

    private void btnTypeContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTypeContinueActionPerformed
        //  Continue button on Floor type selector page
        if(evt.getSource() == btnTypeContinue) {
     // check if we are at zero //
     if(tPCustomer.getSelectedIndex() == 0)
       tPCustomer.setSelectedIndex( tPCustomer.getTabCount() -1);
     else
       tPCustomer.setSelectedIndex(tPCustomer.getSelectedIndex() +1);

  }
    }//GEN-LAST:event_btnTypeContinueActionPerformed

    private void tPCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPCustomerMouseClicked

    }//GEN-LAST:event_tPCustomerMouseClicked

    private void btnADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADMINActionPerformed
        //access orderTable
        String admin = JOptionPane.showInputDialog(this, "Enter User Name");
        String adminPass = JOptionPane.showInputDialog(this, "Enter Password");
        if(admin.equals("Payden") && adminPass.equals("testing"))
        {
         int index = tPCustomer.indexOfTab("Order Table");
        tPCustomer.setEnabledAt(index,true);
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "ERROR INVALID PASSWORD","ACCESS DENIED!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnADMINActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(FloorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(FloorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(FloorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(FloorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FloorGUI().setVisible(true);
                }
            });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaTextField;
    private javax.swing.JButton btnADMIN;
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnCusContinue;
    private javax.swing.JMenuItem btnGit;
    private javax.swing.ButtonGroup btnGroupFloor;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnTypeBack;
    private javax.swing.JButton btnTypeContinue;
    private javax.swing.JRadioButton carpetRadBtn;
    private javax.swing.JComboBox<String> cbState;
    private javax.swing.JTextField costTextField;
    private javax.swing.JTable customerTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpCustomerInfo;
    private javax.swing.JPanel jpFloorSelector;
    private javax.swing.JPanel jpOrder;
    private javax.swing.JLabel lblAddr;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblFloorArea1;
    private javax.swing.JLabel lblFloorCost1;
    private javax.swing.JLabel lblFloorEstimatorLogo;
    private javax.swing.JLabel lblFloorSelector;
    private javax.swing.JLabel lblFloorType;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblSummary;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JTextField lenTextField;
    private javax.swing.JTabbedPane tPCustomer;
    private javax.swing.JTextArea txaOrderSummary;
    private javax.swing.JTextField txfAddr;
    private javax.swing.JTextField txfCity;
    private javax.swing.JTextField txfFName;
    private javax.swing.JTextField txfLName;
    private javax.swing.JTextField widTextField;
    private javax.swing.JRadioButton woodRadBtn;
    // End of variables declaration//GEN-END:variables

    private void Ldata() {
        DefaultTableModel mod = new DefaultTableModel(new String[]{"CustomerName", "CustomerAddress", "FloorType", "FloorArea", "FloorCost"}, 0);
        DataIO data = new DataIO();

        try {
            mod = data.loadData();
        } catch (SQLException ex) {
            Logger.getLogger(FloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        customerTable.setModel(mod);
    }

    private void secur() {
        int index = tPCustomer.indexOfTab("Order Table");
        tPCustomer.setEnabledAt(index,false);
        
        
    }
}
